# Generated by Django 4.1.7 on 2023-05-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
